import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Generates src/wasm-inline.ts: a base64-embedded copy of the compiled WASM
// binary so the loader can initialize synchronously with no runtime filesystem
// read. This keeps the package working in standalone-binary / bundler contexts
// where the sibling .wasm asset is not available on disk at runtime.
//
// The generated file is gitignored and regenerated on every `build:wasm`, so it
// always matches the freshly built binary (no drift, nothing committed).

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const wasmPath = path.join(rootDir, 'pkg', 'web', 'string_metrics_wasm_bg.wasm');
const outPath = path.join(rootDir, 'src', 'wasm-inline.ts');

const wasmBytes = await fs.readFile(wasmPath);
const base64 = wasmBytes.toString('base64');

// The `: string` annotation is deliberate: without it tsc infers the entire
// base64 string literal as the declared type and emits a ~300 KB .d.ts (which
// also slows consumer typechecking). Typing it as `string` keeps the generated
// declaration a single line.
const contents = `// AUTO-GENERATED by scripts/embed-wasm.js during \`npm run build:wasm\`. Do not edit.
// Base64-encoded copy of pkg/web/string_metrics_wasm_bg.wasm, embedded so the
// loader can initialize synchronously without a runtime filesystem read.
export const WASM_BASE64: string =
  '${base64}';
`;

await fs.writeFile(outPath, contents, 'utf8');
console.log(
  `[embed-wasm] Wrote ${path.relative(rootDir, outPath)} (${wasmBytes.length} bytes -> ${base64.length} base64 chars)`,
);
